// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Version {
    #[prost(uint32, optional, tag = "1")]
    pub version_v1: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "5")]
    pub version_v2: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "2")]
    pub release: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub os: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub os_version: ::core::option::Option<::prost::alloc::string::String>,
    /// Fancy Mumble version identifier using v2 encoding:
    /// (major << 48) | (minor << 32) | (patch << 16).
    /// When present, both sides understand extensions
    /// (message_id, timestamp, etc.).
    #[prost(uint64, optional, tag = "6")]
    pub fancy_version: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UdpTunnel {
    #[prost(bytes = "vec", required, tag = "1")]
    pub packet: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Authenticate {
    #[prost(string, optional, tag = "1")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub tokens: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub celt_versions: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, optional, tag = "5", default = "false")]
    pub opus: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "6", default = "0")]
    pub client_type: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Ping {
    #[prost(uint64, optional, tag = "1")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "2")]
    pub good: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub late: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub lost: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub resync: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "6")]
    pub udp_packets: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub tcp_packets: ::core::option::Option<u32>,
    #[prost(float, optional, tag = "8")]
    pub udp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "9")]
    pub udp_ping_var: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "10")]
    pub tcp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "11")]
    pub tcp_ping_var: ::core::option::Option<f32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reject {
    #[prost(enumeration = "reject::RejectType", optional, tag = "1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `Reject`.
pub mod reject {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum RejectType {
        None = 0,
        WrongVersion = 1,
        InvalidUsername = 2,
        WrongUserPw = 3,
        WrongServerPw = 4,
        UsernameInUse = 5,
        ServerFull = 6,
        NoCertificate = 7,
        AuthenticatorFail = 8,
        NoNewConnections = 9,
    }
    impl RejectType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::None => "None",
                Self::WrongVersion => "WrongVersion",
                Self::InvalidUsername => "InvalidUsername",
                Self::WrongUserPw => "WrongUserPW",
                Self::WrongServerPw => "WrongServerPW",
                Self::UsernameInUse => "UsernameInUse",
                Self::ServerFull => "ServerFull",
                Self::NoCertificate => "NoCertificate",
                Self::AuthenticatorFail => "AuthenticatorFail",
                Self::NoNewConnections => "NoNewConnections",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "WrongVersion" => Some(Self::WrongVersion),
                "InvalidUsername" => Some(Self::InvalidUsername),
                "WrongUserPW" => Some(Self::WrongUserPw),
                "WrongServerPW" => Some(Self::WrongServerPw),
                "UsernameInUse" => Some(Self::UsernameInUse),
                "ServerFull" => Some(Self::ServerFull),
                "NoCertificate" => Some(Self::NoCertificate),
                "AuthenticatorFail" => Some(Self::AuthenticatorFail),
                "NoNewConnections" => Some(Self::NoNewConnections),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerSync {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub max_bandwidth: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub welcome_text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "4")]
    pub permissions: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelRemove {
    #[prost(uint32, required, tag = "1")]
    pub channel_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelState {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub parent: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, repeated, packed = "false", tag = "4")]
    pub links: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, optional, tag = "5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, repeated, packed = "false", tag = "6")]
    pub links_add: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "7")]
    pub links_remove: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, optional, tag = "8", default = "false")]
    pub temporary: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "9", default = "0")]
    pub position: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "10")]
    pub description_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "11")]
    pub max_users: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "12")]
    pub is_enter_restricted: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "13")]
    pub can_enter: ::core::option::Option<bool>,
    /// Fancy Mumble persistent chat extension.
    /// Field IDs start at 100 to avoid clashing with future upstream
    /// Mumble protocol additions. Legacy clients silently ignore
    /// unknown fields (standard protobuf behaviour).
    /// Protocol and persistence mode for this channel.
    /// Uses the top-level PchatProtocol enum.
    #[prost(enumeration = "PchatProtocol", optional, tag = "100")]
    pub pchat_protocol: ::core::option::Option<i32>,
    /// Maximum number of messages to store (0 = unlimited).
    #[prost(uint32, optional, tag = "101")]
    pub pchat_max_history: ::core::option::Option<u32>,
    /// Auto-delete messages after this many days (0 = forever).
    #[prost(uint32, optional, tag = "102")]
    pub pchat_retention_days: ::core::option::Option<u32>,
    /// Cert hashes of users designated as key custodians for this channel.
    /// Key custodians can countersign epoch transitions and are trusted
    /// authorities for key distribution. Set by channel operators.
    #[prost(string, repeated, tag = "103")]
    pub pchat_key_custodians: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRemove {
    #[prost(uint32, required, tag = "1")]
    pub session: u32,
    #[prost(uint32, optional, tag = "2")]
    pub actor: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub ban: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub ban_certificate: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "6")]
    pub ban_ip: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserState {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub actor: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "4")]
    pub user_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "6")]
    pub mute: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "7")]
    pub deaf: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "8")]
    pub suppress: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "9")]
    pub self_mute: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "10")]
    pub self_deaf: ::core::option::Option<bool>,
    #[prost(bytes = "vec", optional, tag = "11")]
    pub texture: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "12")]
    pub plugin_context: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "13")]
    pub plugin_identity: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub comment: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "15")]
    pub hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "16")]
    pub comment_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "17")]
    pub texture_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, optional, tag = "18")]
    pub priority_speaker: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "19")]
    pub recording: ::core::option::Option<bool>,
    #[prost(string, repeated, tag = "20")]
    pub temporary_access_tokens: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    #[prost(uint32, repeated, packed = "false", tag = "21")]
    pub listening_channel_add: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "22")]
    pub listening_channel_remove: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "23")]
    pub listening_volume_adjustment: ::prost::alloc::vec::Vec<
        user_state::VolumeAdjustment,
    >,
    #[prost(
        enumeration = "user_state::ClientFeature",
        repeated,
        packed = "false",
        tag = "24"
    )]
    pub client_features: ::prost::alloc::vec::Vec<i32>,
}
/// Nested message and enum types in `UserState`.
pub mod user_state {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct VolumeAdjustment {
        #[prost(uint32, optional, tag = "1")]
        pub listening_channel: ::core::option::Option<u32>,
        #[prost(float, optional, tag = "2")]
        pub volume_adjustment: ::core::option::Option<f32>,
    }
    /// Extended client capabilities advertised by the server.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ClientFeature {
        FeaturePchatE2ee = 0,
    }
    impl ClientFeature {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::FeaturePchatE2ee => "FEATURE_PCHAT_E2EE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FEATURE_PCHAT_E2EE" => Some(Self::FeaturePchatE2ee),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BanList {
    #[prost(message, repeated, tag = "1")]
    pub bans: ::prost::alloc::vec::Vec<ban_list::BanEntry>,
    #[prost(bool, optional, tag = "2", default = "false")]
    pub query: ::core::option::Option<bool>,
}
/// Nested message and enum types in `BanList`.
pub mod ban_list {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct BanEntry {
        #[prost(bytes = "vec", required, tag = "1")]
        pub address: ::prost::alloc::vec::Vec<u8>,
        #[prost(uint32, required, tag = "2")]
        pub mask: u32,
        #[prost(string, optional, tag = "3")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub hash: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "5")]
        pub reason: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "6")]
        pub start: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "7")]
        pub duration: ::core::option::Option<u32>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextMessage {
    #[prost(uint32, optional, tag = "1")]
    pub actor: ::core::option::Option<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "2")]
    pub session: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "3")]
    pub channel_id: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "4")]
    pub tree_id: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, required, tag = "5")]
    pub message: ::prost::alloc::string::String,
    /// Unique identifier for this message (Fancy Mumble extension).
    #[prost(string, optional, tag = "6")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Message timestamp as Unix epoch millis (Fancy Mumble extension).
    #[prost(uint64, optional, tag = "7")]
    pub timestamp: ::core::option::Option<u64>,
    /// When set, this message is an edit replacing the message with this ID.
    #[prost(string, optional, tag = "8")]
    pub edit_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PermissionDenied {
    #[prost(uint32, optional, tag = "1")]
    pub permission: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub session: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "permission_denied::DenyType", optional, tag = "5")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "6")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `PermissionDenied`.
pub mod permission_denied {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DenyType {
        Text = 0,
        Permission = 1,
        SuperUser = 2,
        ChannelName = 3,
        TextTooLong = 4,
        H9k = 5,
        TemporaryChannel = 6,
        MissingCertificate = 7,
        UserName = 8,
        ChannelFull = 9,
        NestingLimit = 10,
        ChannelCountLimit = 11,
        ChannelListenerLimit = 12,
        UserListenerLimit = 13,
    }
    impl DenyType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Text => "Text",
                Self::Permission => "Permission",
                Self::SuperUser => "SuperUser",
                Self::ChannelName => "ChannelName",
                Self::TextTooLong => "TextTooLong",
                Self::H9k => "H9K",
                Self::TemporaryChannel => "TemporaryChannel",
                Self::MissingCertificate => "MissingCertificate",
                Self::UserName => "UserName",
                Self::ChannelFull => "ChannelFull",
                Self::NestingLimit => "NestingLimit",
                Self::ChannelCountLimit => "ChannelCountLimit",
                Self::ChannelListenerLimit => "ChannelListenerLimit",
                Self::UserListenerLimit => "UserListenerLimit",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Text" => Some(Self::Text),
                "Permission" => Some(Self::Permission),
                "SuperUser" => Some(Self::SuperUser),
                "ChannelName" => Some(Self::ChannelName),
                "TextTooLong" => Some(Self::TextTooLong),
                "H9K" => Some(Self::H9k),
                "TemporaryChannel" => Some(Self::TemporaryChannel),
                "MissingCertificate" => Some(Self::MissingCertificate),
                "UserName" => Some(Self::UserName),
                "ChannelFull" => Some(Self::ChannelFull),
                "NestingLimit" => Some(Self::NestingLimit),
                "ChannelCountLimit" => Some(Self::ChannelCountLimit),
                "ChannelListenerLimit" => Some(Self::ChannelListenerLimit),
                "UserListenerLimit" => Some(Self::UserListenerLimit),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Acl {
    #[prost(uint32, required, tag = "1")]
    pub channel_id: u32,
    #[prost(bool, optional, tag = "2", default = "true")]
    pub inherit_acls: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "3")]
    pub groups: ::prost::alloc::vec::Vec<acl::ChanGroup>,
    #[prost(message, repeated, tag = "4")]
    pub acls: ::prost::alloc::vec::Vec<acl::ChanAcl>,
    #[prost(bool, optional, tag = "5", default = "false")]
    pub query: ::core::option::Option<bool>,
}
/// Nested message and enum types in `ACL`.
pub mod acl {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ChanGroup {
        #[prost(string, required, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(bool, optional, tag = "2", default = "true")]
        pub inherited: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "3", default = "true")]
        pub inherit: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "4", default = "true")]
        pub inheritable: ::core::option::Option<bool>,
        #[prost(uint32, repeated, packed = "false", tag = "5")]
        pub add: ::prost::alloc::vec::Vec<u32>,
        #[prost(uint32, repeated, packed = "false", tag = "6")]
        pub remove: ::prost::alloc::vec::Vec<u32>,
        #[prost(uint32, repeated, packed = "false", tag = "7")]
        pub inherited_members: ::prost::alloc::vec::Vec<u32>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ChanAcl {
        #[prost(bool, optional, tag = "1", default = "true")]
        pub apply_here: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "2", default = "true")]
        pub apply_subs: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "3", default = "true")]
        pub inherited: ::core::option::Option<bool>,
        #[prost(uint32, optional, tag = "4")]
        pub user_id: ::core::option::Option<u32>,
        #[prost(string, optional, tag = "5")]
        pub group: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "6")]
        pub grant: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "7")]
        pub deny: ::core::option::Option<u32>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryUsers {
    #[prost(uint32, repeated, packed = "false", tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CryptSetup {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub client_nonce: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub server_nonce: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContextActionModify {
    #[prost(string, required, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub context: ::core::option::Option<u32>,
    #[prost(enumeration = "context_action_modify::Operation", optional, tag = "4")]
    pub operation: ::core::option::Option<i32>,
}
/// Nested message and enum types in `ContextActionModify`.
pub mod context_action_modify {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Context {
        Server = 1,
        Channel = 2,
        User = 4,
    }
    impl Context {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Server => "Server",
                Self::Channel => "Channel",
                Self::User => "User",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Server" => Some(Self::Server),
                "Channel" => Some(Self::Channel),
                "User" => Some(Self::User),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Operation {
        Add = 0,
        Remove = 1,
    }
    impl Operation {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Add => "Add",
                Self::Remove => "Remove",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Add" => Some(Self::Add),
                "Remove" => Some(Self::Remove),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContextAction {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(string, required, tag = "3")]
    pub action: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserList {
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<user_list::User>,
}
/// Nested message and enum types in `UserList`.
pub mod user_list {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct User {
        #[prost(uint32, required, tag = "1")]
        pub user_id: u32,
        #[prost(string, optional, tag = "2")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub last_seen: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "4")]
        pub last_channel: ::core::option::Option<u32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoiceTarget {
    #[prost(uint32, optional, tag = "1")]
    pub id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub targets: ::prost::alloc::vec::Vec<voice_target::Target>,
}
/// Nested message and enum types in `VoiceTarget`.
pub mod voice_target {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Target {
        #[prost(uint32, repeated, packed = "false", tag = "1")]
        pub session: ::prost::alloc::vec::Vec<u32>,
        #[prost(uint32, optional, tag = "2")]
        pub channel_id: ::core::option::Option<u32>,
        #[prost(string, optional, tag = "3")]
        pub group: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(bool, optional, tag = "4", default = "false")]
        pub links: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "5", default = "false")]
        pub children: ::core::option::Option<bool>,
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PermissionQuery {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub permissions: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "3", default = "false")]
    pub flush: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CodecVersion {
    #[prost(int32, required, tag = "1")]
    pub alpha: i32,
    #[prost(int32, required, tag = "2")]
    pub beta: i32,
    #[prost(bool, required, tag = "3", default = "true")]
    pub prefer_alpha: bool,
    #[prost(bool, optional, tag = "4", default = "false")]
    pub opus: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserStats {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "2", default = "false")]
    pub stats_only: ::core::option::Option<bool>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub certificates: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "4")]
    pub from_client: ::core::option::Option<user_stats::Stats>,
    #[prost(message, optional, tag = "5")]
    pub from_server: ::core::option::Option<user_stats::Stats>,
    #[prost(uint32, optional, tag = "6")]
    pub udp_packets: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub tcp_packets: ::core::option::Option<u32>,
    #[prost(float, optional, tag = "8")]
    pub udp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "9")]
    pub udp_ping_var: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "10")]
    pub tcp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "11")]
    pub tcp_ping_var: ::core::option::Option<f32>,
    #[prost(message, optional, tag = "12")]
    pub version: ::core::option::Option<Version>,
    #[prost(int32, repeated, packed = "false", tag = "13")]
    pub celt_versions: ::prost::alloc::vec::Vec<i32>,
    #[prost(bytes = "vec", optional, tag = "14")]
    pub address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "15")]
    pub bandwidth: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "16")]
    pub onlinesecs: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "17")]
    pub idlesecs: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "18", default = "false")]
    pub strong_certificate: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "19", default = "false")]
    pub opus: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "20")]
    pub rolling_stats: ::core::option::Option<user_stats::RollingStats>,
}
/// Nested message and enum types in `UserStats`.
pub mod user_stats {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Stats {
        #[prost(uint32, optional, tag = "1")]
        pub good: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "2")]
        pub late: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "3")]
        pub lost: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "4")]
        pub resync: ::core::option::Option<u32>,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RollingStats {
        #[prost(uint32, optional, tag = "1")]
        pub time_window: ::core::option::Option<u32>,
        #[prost(message, optional, tag = "2")]
        pub from_client: ::core::option::Option<Stats>,
        #[prost(message, optional, tag = "3")]
        pub from_server: ::core::option::Option<Stats>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestBlob {
    #[prost(uint32, repeated, packed = "false", tag = "1")]
    pub session_texture: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "2")]
    pub session_comment: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "3")]
    pub channel_description: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerConfig {
    #[prost(uint32, optional, tag = "1")]
    pub max_bandwidth: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub welcome_text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "3")]
    pub allow_html: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub message_length: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub image_message_length: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "6")]
    pub max_users: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "7")]
    pub recording_allowed: ::core::option::Option<bool>,
    /// True when the server has a WebRTC SFU module loaded and can
    /// relay screen-share streams server-side.
    #[prost(bool, optional, tag = "8")]
    pub webrtc_sfu_available: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SuggestConfig {
    #[prost(uint32, optional, tag = "1")]
    pub version_v1: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "4")]
    pub version_v2: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "2")]
    pub positional: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub push_to_talk: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginDataTransmission {
    #[prost(uint32, optional, tag = "1")]
    pub sender_session: ::core::option::Option<u32>,
    #[prost(uint32, repeated, tag = "2")]
    pub receiver_sessions: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "4")]
    pub data_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Encrypted persistent chat message sent from client to server for storage.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatMessage {
    #[prost(string, optional, tag = "1")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "3")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "4")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "PchatProtocol", optional, tag = "5")]
    pub protocol: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub envelope: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "7")]
    pub epoch: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "8")]
    pub chain_index: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "9")]
    pub epoch_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "10")]
    pub replaces_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request stored messages from the server.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatFetch {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub before_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub limit: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub after_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Server response to a PchatFetch request.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PchatFetchResponse {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<PchatMessage>,
    #[prost(bool, optional, tag = "3")]
    pub has_more: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub total_stored: ::core::option::Option<u32>,
}
/// Server relays a new message to other clients in the channel.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatMessageDeliver {
    #[prost(string, optional, tag = "1")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "3")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "4")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "PchatProtocol", optional, tag = "5")]
    pub protocol: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub envelope: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "7")]
    pub replaces_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Client announcement of E2EE identity public keys.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyAnnounce {
    #[prost(uint32, optional, tag = "1")]
    pub algorithm_version: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub identity_public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub signing_public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "4")]
    pub cert_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "5")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "7")]
    pub tls_signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Peer-to-peer key exchange relayed through the server.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyExchange {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(enumeration = "PchatProtocol", optional, tag = "2")]
    pub protocol: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag = "3")]
    pub epoch: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub encrypted_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "5")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub recipient_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "8")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "9")]
    pub algorithm_version: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "10")]
    pub signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "11")]
    pub parent_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "12")]
    pub epoch_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "13")]
    pub countersignature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "14")]
    pub countersigner_hash: ::core::option::Option<::prost::alloc::string::String>,
}
/// Server-broadcast key request when a new member joins a persistent channel.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyRequest {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(enumeration = "PchatProtocol", optional, tag = "2")]
    pub protocol: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub requester_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub requester_public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "5")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "6")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "7")]
    pub relay_cap: ::core::option::Option<u32>,
}
/// Server acknowledgement of message storage or deletion.
/// For storage (PCHAT_ACK_STORED): message_ids contains the single stored message ID.
/// For deletion (PCHAT_ACK_DELETED): message_ids lists all deleted IDs,
/// reason carries the deleted count as a decimal string.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatAck {
    #[prost(string, repeated, tag = "1")]
    pub message_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "PchatAckStatus", optional, tag = "2")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    /// Channel ID for scoped acks (e.g. offline queue acknowledgement).
    #[prost(uint32, optional, tag = "4")]
    pub channel_id: ::core::option::Option<u32>,
}
/// Key custodian countersignature on an epoch transition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatEpochCountersig {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub epoch: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub epoch_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub parent_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "5")]
    pub signer_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub distributor_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "7")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "8")]
    pub countersignature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Client reports to the server that a cert_hash now holds the E2EE key
/// for a channel.  Sent after distributing or receiving a key.
/// Wire type ID = 109.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyHolderReport {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// The cert hash of the user that now holds the key.
    #[prost(string, optional, tag = "2")]
    pub cert_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// When set, the sender (with KeyOwner permission) requests a
    /// key-ownership takeover.  Omit for a normal key-holder report.
    #[prost(
        enumeration = "pchat_key_holder_report::KeyTakeoverMode",
        optional,
        tag = "3"
    )]
    pub takeover_mode: ::core::option::Option<i32>,
}
/// Nested message and enum types in `PchatKeyHolderReport`.
pub mod pchat_key_holder_report {
    /// How the key-ownership takeover should be performed.
    /// Requires KeyOwner permission when set.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum KeyTakeoverMode {
        /// Full wipe: delete all stored messages, remove all known key
        /// holders, reset challenge state, record sender as sole holder.
        FullWipe = 1,
        /// Key-only takeover: remove all known key holders and reset
        /// challenge state, but keep stored messages intact.
        KeyOnly = 2,
    }
    impl KeyTakeoverMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::FullWipe => "FULL_WIPE",
                Self::KeyOnly => "KEY_ONLY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FULL_WIPE" => Some(Self::FullWipe),
                "KEY_ONLY" => Some(Self::KeyOnly),
                _ => None,
            }
        }
    }
}
/// Client asks the server for all known key holders of a channel.
/// Wire type ID = 110.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyHoldersQuery {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
}
/// Server responds with the full list of key holders for a channel.
/// Wire type ID = 111.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PchatKeyHoldersList {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub holders: ::prost::alloc::vec::Vec<pchat_key_holders_list::Entry>,
}
/// Nested message and enum types in `PchatKeyHoldersList`.
pub mod pchat_key_holders_list {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Entry {
        /// TLS certificate hash (hex-encoded SHA-1).
        #[prost(string, optional, tag = "1")]
        pub cert_hash: ::core::option::Option<::prost::alloc::string::String>,
        /// Last known username (server fills from UserState if available).
        #[prost(string, optional, tag = "2")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
    }
}
/// Server sends a challenge to a client after it reports as a key holder.
/// The client must prove it holds the correct key by computing
/// HMAC-SHA256(channel_key, challenge) and returning it.
/// Wire type ID = 112.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyChallenge {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// 32-byte random challenge nonce.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub challenge: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Client response to PchatKeyChallenge with the HMAC proof.
/// Wire type ID = 113.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyChallengeResponse {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// HMAC-SHA256(channel_key, challenge).
    #[prost(bytes = "vec", optional, tag = "2")]
    pub proof: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Server informs the client whether the challenge was passed.
/// Wire type ID = 114.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyChallengeResult {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "2")]
    pub passed: ::core::option::Option<bool>,
}
/// Client requests deletion of persistent messages in a channel.
/// Exactly one deletion mode should be used per request:
/// message_ids for bulk delete, time_range for range delete,
/// or sender_hash for user delete.
/// Server acknowledges via PchatAck with status PCHAT_ACK_DELETED,
/// message_ids listing deleted IDs, then broadcasts this same
/// PchatDeleteMessages to other verified sessions so they can
/// evict matching messages locally. Wire type ID = 115.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatDeleteMessages {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// Bulk delete: specific message IDs to remove.
    #[prost(string, repeated, tag = "2")]
    pub message_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Range delete: remove messages within the given time window.
    #[prost(message, optional, tag = "3")]
    pub time_range: ::core::option::Option<pchat_delete_messages::TimeRange>,
    /// User delete: remove all messages from this sender cert hash.
    #[prost(string, optional, tag = "4")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `PchatDeleteMessages`.
pub mod pchat_delete_messages {
    /// Inclusive timestamp range for range-based deletion.
    /// Both bounds are Unix epoch milliseconds.
    /// Omit either bound to leave it open-ended.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct TimeRange {
        #[prost(uint64, optional, tag = "1")]
        pub from: ::core::option::Option<u64>,
        #[prost(uint64, optional, tag = "2")]
        pub to: ::core::option::Option<u64>,
    }
}
/// Server delivers queued offline messages to a client that has reconnected
/// and passed the key-possession challenge for a SignalV1 channel.
/// Encrypted envelopes are delivered in timestamp order.
/// The client acknowledges receipt via PchatAck (which already supports
/// multiple message IDs). The server permanently deletes acknowledged
/// entries from the queue.
/// Wire type ID = 116.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PchatOfflineQueueDrain {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// Queued messages, each as a PchatMessageDeliver.
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<PchatMessageDeliver>,
    /// Sender key distributions needed to decrypt the queued messages.
    /// The client MUST process these before attempting to decrypt
    /// the messages above.
    #[prost(message, repeated, tag = "3")]
    pub distributions: ::prost::alloc::vec::Vec<PchatSenderKeyDistribution>,
}
/// A standard Unicode emoji (grapheme cluster, e.g. "\xF0\x9F\x91\x8D").
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnicodeEmoji {
    #[prost(string, optional, tag = "1")]
    pub grapheme: ::core::option::Option<::prost::alloc::string::String>,
}
/// A server-specific custom emoji referenced by shortcode.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerEmoji {
    /// Short code identifier without colons (e.g. "mumble_parrot").
    #[prost(bytes = "vec", optional, tag = "1")]
    pub shortcode: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Client -> Server: add or remove an emoji reaction on a persisted message.
/// The server validates sender_hash against the session, stores the
/// reaction (or removes it), and broadcasts a PchatReactionDeliver to
/// all Fancy clients in the channel.
/// Wire type ID = 117.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatReaction {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// Target message ID (must be a valid stored message in this channel).
    #[prost(string, optional, tag = "2")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "ReactionAction", optional, tag = "5")]
    pub action: ::core::option::Option<i32>,
    /// TLS cert hash of the reactor (server validates against session).
    #[prost(string, optional, tag = "6")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// Client-supplied timestamp (ms since epoch); server may override.
    #[prost(uint64, optional, tag = "7")]
    pub timestamp: ::core::option::Option<u64>,
    /// The emoji being reacted with.
    #[prost(oneof = "pchat_reaction::Emoji", tags = "3, 4")]
    pub emoji: ::core::option::Option<pchat_reaction::Emoji>,
}
/// Nested message and enum types in `PchatReaction`.
pub mod pchat_reaction {
    /// The emoji being reacted with.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Emoji {
        #[prost(message, tag = "3")]
        UnicodeEmoji(super::UnicodeEmoji),
        #[prost(message, tag = "4")]
        ServerEmoji(super::ServerEmoji),
    }
}
/// Server -> Client: delivers a reaction add/remove event.
/// Broadcast to all Fancy clients in the channel after a valid PchatReaction.
/// Wire type ID = 118.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatReactionDeliver {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "ReactionAction", optional, tag = "3")]
    pub action: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// Best-effort display name of the reactor.
    #[prost(string, optional, tag = "5")]
    pub sender_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "6")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(oneof = "pchat_reaction_deliver::Emoji", tags = "10, 11")]
    pub emoji: ::core::option::Option<pchat_reaction_deliver::Emoji>,
}
/// Nested message and enum types in `PchatReactionDeliver`.
pub mod pchat_reaction_deliver {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Emoji {
        #[prost(message, tag = "10")]
        UnicodeEmoji(super::UnicodeEmoji),
        #[prost(message, tag = "11")]
        ServerEmoji(super::ServerEmoji),
    }
}
/// Server -> Client: batch delivery of all stored reactions for messages
/// in a channel. Sent in response to PchatFetchResponse so the client
/// can populate reaction pills for historical messages.
/// Wire type ID = 119.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PchatReactionFetchResponse {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub reactions: ::prost::alloc::vec::Vec<
        pchat_reaction_fetch_response::StoredReaction,
    >,
}
/// Nested message and enum types in `PchatReactionFetchResponse`.
pub mod pchat_reaction_fetch_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct StoredReaction {
        #[prost(string, optional, tag = "1")]
        pub message_id: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub sender_name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint64, optional, tag = "4")]
        pub timestamp: ::core::option::Option<u64>,
        #[prost(oneof = "stored_reaction::Emoji", tags = "10, 11")]
        pub emoji: ::core::option::Option<stored_reaction::Emoji>,
    }
    /// Nested message and enum types in `StoredReaction`.
    pub mod stored_reaction {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
        pub enum Emoji {
            #[prost(message, tag = "10")]
            UnicodeEmoji(super::super::UnicodeEmoji),
            #[prost(message, tag = "11")]
            ServerEmoji(super::super::ServerEmoji),
        }
    }
}
/// Bidirectional signaling message for WebRTC screen-share sessions.
/// The server acts as a relay: it fills in sender_session and forwards
/// the message to target_session unchanged.
/// Wire type ID = 120.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebRtcSignal {
    /// Session ID of the intended recipient (0 = broadcast to channel).
    #[prost(uint32, optional, tag = "1")]
    pub target_session: ::core::option::Option<u32>,
    /// Session ID of the sender (set by server, ignored from client).
    #[prost(uint32, optional, tag = "2")]
    pub sender_session: ::core::option::Option<u32>,
    #[prost(enumeration = "web_rtc_signal::SignalType", optional, tag = "3")]
    pub signal_type: ::core::option::Option<i32>,
    /// SDP or ICE candidate string (JSON-encoded for ICE).
    #[prost(string, optional, tag = "4")]
    pub payload: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `WebRtcSignal`.
pub mod web_rtc_signal {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SignalType {
        Start = 0,
        Stop = 1,
        SdpOffer = 2,
        SdpAnswer = 3,
        IceCandidate = 4,
    }
    impl SignalType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Start => "START",
                Self::Stop => "STOP",
                Self::SdpOffer => "SDP_OFFER",
                Self::SdpAnswer => "SDP_ANSWER",
                Self::IceCandidate => "ICE_CANDIDATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "START" => Some(Self::Start),
                "STOP" => Some(Self::Stop),
                "SDP_OFFER" => Some(Self::SdpOffer),
                "SDP_ANSWER" => Some(Self::SdpAnswer),
                "ICE_CANDIDATE" => Some(Self::IceCandidate),
                _ => None,
            }
        }
    }
}
/// Client sends its Signal sender key distribution to the server for
/// relay to channel members and storage for offline delivery.
/// Replaces the previous PluginData-based distribution mechanism.
/// Wire type ID = 121.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatSenderKeyDistribution {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    /// TLS certificate hash of the sender (server fills on relay).
    #[prost(string, optional, tag = "2")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// Sender Key Distribution Message bytes (libsignal SKDM).
    #[prost(bytes = "vec", optional, tag = "3")]
    pub distribution: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Client registers its FCM device token with the server for push
/// notifications. Sent once after ServerSync on Android.
/// Wire type ID = 122.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FancyPushRegister {
    /// FCM device registration token.
    #[prost(string, optional, tag = "1")]
    pub token: ::core::option::Option<::prost::alloc::string::String>,
    /// Channel IDs the client has muted for push notifications.
    #[prost(uint32, repeated, tag = "2")]
    pub muted_channels: ::prost::alloc::vec::Vec<u32>,
}
/// Client updates its per-channel push notification mute preferences.
/// Sent when the user toggles push mute on a channel.
/// Wire type ID = 123.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FancyPushUpdate {
    /// Complete list of channel IDs muted for push notifications.
    #[prost(uint32, repeated, tag = "1")]
    pub muted_channels: ::prost::alloc::vec::Vec<u32>,
}
/// Client requests live message delivery from channels where it has the
/// SubscribePush permission (0x2000). Analogous to FancyPushRegister but
/// for connected clients: the server computes allowed channels and routes
/// TextMessages to the subscriber without requiring ChannelListen.
/// Wire type ID = 125.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FancySubscribePush {
    /// Channel IDs the client wants to exclude from live delivery.
    #[prost(uint32, repeated, tag = "1")]
    pub muted_channels: ::prost::alloc::vec::Vec<u32>,
}
/// Server broadcasts its custom emoji/reaction configuration to clients
/// after connect. Replaces the previous PluginData-based delivery.
/// Wire type ID = 124.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FancyCustomReactionsConfig {
    #[prost(message, repeated, tag = "1")]
    pub reactions: ::prost::alloc::vec::Vec<
        fancy_custom_reactions_config::CustomReaction,
    >,
}
/// Nested message and enum types in `FancyCustomReactionsConfig`.
pub mod fancy_custom_reactions_config {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct CustomReaction {
        /// Short-code identifier without colons (e.g. "mumble_parrot").
        #[prost(string, optional, tag = "1")]
        pub shortcode: ::core::option::Option<::prost::alloc::string::String>,
        /// Display string (emoji char, image URL, or unicode).
        #[prost(string, optional, tag = "2")]
        pub display: ::core::option::Option<::prost::alloc::string::String>,
        /// Optional human-readable label.
        #[prost(string, optional, tag = "3")]
        pub label: ::core::option::Option<::prost::alloc::string::String>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FancyReadReceipt {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub last_read_message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "3")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "4")]
    pub query: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "5")]
    pub query_message_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FancyReadReceiptDeliver {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub read_states: ::prost::alloc::vec::Vec<fancy_read_receipt_deliver::ReadState>,
    #[prost(string, optional, tag = "3")]
    pub query_message_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `FancyReadReceiptDeliver`.
pub mod fancy_read_receipt_deliver {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ReadState {
        #[prost(string, optional, tag = "1")]
        pub cert_hash: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub last_read_message_id: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint64, optional, tag = "4")]
        pub timestamp: ::core::option::Option<u64>,
    }
}
/// Unified pchat protocol indicator.
/// Each value identifies both the E2EE protocol implementation
/// and the persistence behaviour for a channel.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PchatProtocol {
    None = 0,
    FancyV1FullArchive = 2,
    SignalV1 = 4,
}
impl PchatProtocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "PCHAT_PROTOCOL_NONE",
            Self::FancyV1FullArchive => "PCHAT_PROTOCOL_FANCY_V1_FULL_ARCHIVE",
            Self::SignalV1 => "PCHAT_PROTOCOL_SIGNAL_V1",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PCHAT_PROTOCOL_NONE" => Some(Self::None),
            "PCHAT_PROTOCOL_FANCY_V1_FULL_ARCHIVE" => Some(Self::FancyV1FullArchive),
            "PCHAT_PROTOCOL_SIGNAL_V1" => Some(Self::SignalV1),
            _ => None,
        }
    }
}
/// Ack status for PchatAck.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PchatAckStatus {
    PchatAckStored = 0,
    PchatAckRejected = 1,
    PchatAckQuotaExceeded = 2,
    PchatAckDeleted = 3,
}
impl PchatAckStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PchatAckStored => "PCHAT_ACK_STORED",
            Self::PchatAckRejected => "PCHAT_ACK_REJECTED",
            Self::PchatAckQuotaExceeded => "PCHAT_ACK_QUOTA_EXCEEDED",
            Self::PchatAckDeleted => "PCHAT_ACK_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PCHAT_ACK_STORED" => Some(Self::PchatAckStored),
            "PCHAT_ACK_REJECTED" => Some(Self::PchatAckRejected),
            "PCHAT_ACK_QUOTA_EXCEEDED" => Some(Self::PchatAckQuotaExceeded),
            "PCHAT_ACK_DELETED" => Some(Self::PchatAckDeleted),
            _ => None,
        }
    }
}
/// Reaction action type.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReactionAction {
    ReactionAdd = 0,
    ReactionRemove = 1,
}
impl ReactionAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ReactionAdd => "REACTION_ADD",
            Self::ReactionRemove => "REACTION_REMOVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REACTION_ADD" => Some(Self::ReactionAdd),
            "REACTION_REMOVE" => Some(Self::ReactionRemove),
            _ => None,
        }
    }
}
