// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Version {
    #[prost(uint32, optional, tag = "1")]
    pub version_v1: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "5")]
    pub version_v2: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "2")]
    pub release: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub os: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub os_version: ::core::option::Option<::prost::alloc::string::String>,
    /// Fancy Mumble version identifier using v2 encoding:
    /// (major << 48) | (minor << 32) | (patch << 16).
    /// When present, both sides understand extensions
    /// (message_id, timestamp, etc.).
    #[prost(uint64, optional, tag = "6")]
    pub fancy_version: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UdpTunnel {
    #[prost(bytes = "vec", required, tag = "1")]
    pub packet: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Authenticate {
    #[prost(string, optional, tag = "1")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub tokens: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub celt_versions: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, optional, tag = "5", default = "false")]
    pub opus: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "6", default = "0")]
    pub client_type: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Ping {
    #[prost(uint64, optional, tag = "1")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "2")]
    pub good: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub late: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub lost: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub resync: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "6")]
    pub udp_packets: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub tcp_packets: ::core::option::Option<u32>,
    #[prost(float, optional, tag = "8")]
    pub udp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "9")]
    pub udp_ping_var: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "10")]
    pub tcp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "11")]
    pub tcp_ping_var: ::core::option::Option<f32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reject {
    #[prost(enumeration = "reject::RejectType", optional, tag = "1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `Reject`.
pub mod reject {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum RejectType {
        None = 0,
        WrongVersion = 1,
        InvalidUsername = 2,
        WrongUserPw = 3,
        WrongServerPw = 4,
        UsernameInUse = 5,
        ServerFull = 6,
        NoCertificate = 7,
        AuthenticatorFail = 8,
        NoNewConnections = 9,
    }
    impl RejectType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::None => "None",
                Self::WrongVersion => "WrongVersion",
                Self::InvalidUsername => "InvalidUsername",
                Self::WrongUserPw => "WrongUserPW",
                Self::WrongServerPw => "WrongServerPW",
                Self::UsernameInUse => "UsernameInUse",
                Self::ServerFull => "ServerFull",
                Self::NoCertificate => "NoCertificate",
                Self::AuthenticatorFail => "AuthenticatorFail",
                Self::NoNewConnections => "NoNewConnections",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "WrongVersion" => Some(Self::WrongVersion),
                "InvalidUsername" => Some(Self::InvalidUsername),
                "WrongUserPW" => Some(Self::WrongUserPw),
                "WrongServerPW" => Some(Self::WrongServerPw),
                "UsernameInUse" => Some(Self::UsernameInUse),
                "ServerFull" => Some(Self::ServerFull),
                "NoCertificate" => Some(Self::NoCertificate),
                "AuthenticatorFail" => Some(Self::AuthenticatorFail),
                "NoNewConnections" => Some(Self::NoNewConnections),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerSync {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub max_bandwidth: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub welcome_text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "4")]
    pub permissions: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelRemove {
    #[prost(uint32, required, tag = "1")]
    pub channel_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelState {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub parent: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, repeated, packed = "false", tag = "4")]
    pub links: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, optional, tag = "5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, repeated, packed = "false", tag = "6")]
    pub links_add: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "7")]
    pub links_remove: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, optional, tag = "8", default = "false")]
    pub temporary: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "9", default = "0")]
    pub position: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "10")]
    pub description_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "11")]
    pub max_users: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "12")]
    pub is_enter_restricted: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "13")]
    pub can_enter: ::core::option::Option<bool>,
    /// Persistence mode for this channel.
    #[prost(enumeration = "channel_state::PchatMode", optional, tag = "100")]
    pub pchat_mode: ::core::option::Option<i32>,
    /// Maximum number of messages to store (0 = unlimited).
    #[prost(uint32, optional, tag = "101")]
    pub pchat_max_history: ::core::option::Option<u32>,
    /// Auto-delete messages after this many days (0 = forever).
    #[prost(uint32, optional, tag = "102")]
    pub pchat_retention_days: ::core::option::Option<u32>,
    /// Cert hashes of users designated as key custodians for this channel.
    /// Key custodians can countersign epoch transitions and are trusted
    /// authorities for key distribution. Set by channel operators.
    #[prost(string, repeated, tag = "103")]
    pub pchat_key_custodians: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Nested message and enum types in `ChannelState`.
pub mod channel_state {
    /// Fancy Mumble persistent chat extension.
    /// Field IDs start at 100 to avoid clashing with future upstream
    /// Mumble protocol additions. Legacy clients silently ignore
    /// unknown fields (standard protobuf behaviour).
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PchatMode {
        PchatNone = 0,
        PchatPostJoin = 1,
        PchatFullArchive = 2,
        PchatServerManaged = 3,
    }
    impl PchatMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::PchatNone => "PCHAT_NONE",
                Self::PchatPostJoin => "PCHAT_POST_JOIN",
                Self::PchatFullArchive => "PCHAT_FULL_ARCHIVE",
                Self::PchatServerManaged => "PCHAT_SERVER_MANAGED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PCHAT_NONE" => Some(Self::PchatNone),
                "PCHAT_POST_JOIN" => Some(Self::PchatPostJoin),
                "PCHAT_FULL_ARCHIVE" => Some(Self::PchatFullArchive),
                "PCHAT_SERVER_MANAGED" => Some(Self::PchatServerManaged),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRemove {
    #[prost(uint32, required, tag = "1")]
    pub session: u32,
    #[prost(uint32, optional, tag = "2")]
    pub actor: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub ban: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub ban_certificate: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "6")]
    pub ban_ip: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserState {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub actor: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "4")]
    pub user_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "6")]
    pub mute: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "7")]
    pub deaf: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "8")]
    pub suppress: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "9")]
    pub self_mute: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "10")]
    pub self_deaf: ::core::option::Option<bool>,
    #[prost(bytes = "vec", optional, tag = "11")]
    pub texture: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "12")]
    pub plugin_context: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "13")]
    pub plugin_identity: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub comment: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "15")]
    pub hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "16")]
    pub comment_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "17")]
    pub texture_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, optional, tag = "18")]
    pub priority_speaker: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "19")]
    pub recording: ::core::option::Option<bool>,
    #[prost(string, repeated, tag = "20")]
    pub temporary_access_tokens: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    #[prost(uint32, repeated, packed = "false", tag = "21")]
    pub listening_channel_add: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "22")]
    pub listening_channel_remove: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "23")]
    pub listening_volume_adjustment: ::prost::alloc::vec::Vec<
        user_state::VolumeAdjustment,
    >,
}
/// Nested message and enum types in `UserState`.
pub mod user_state {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct VolumeAdjustment {
        #[prost(uint32, optional, tag = "1")]
        pub listening_channel: ::core::option::Option<u32>,
        #[prost(float, optional, tag = "2")]
        pub volume_adjustment: ::core::option::Option<f32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BanList {
    #[prost(message, repeated, tag = "1")]
    pub bans: ::prost::alloc::vec::Vec<ban_list::BanEntry>,
    #[prost(bool, optional, tag = "2", default = "false")]
    pub query: ::core::option::Option<bool>,
}
/// Nested message and enum types in `BanList`.
pub mod ban_list {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct BanEntry {
        #[prost(bytes = "vec", required, tag = "1")]
        pub address: ::prost::alloc::vec::Vec<u8>,
        #[prost(uint32, required, tag = "2")]
        pub mask: u32,
        #[prost(string, optional, tag = "3")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub hash: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "5")]
        pub reason: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "6")]
        pub start: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "7")]
        pub duration: ::core::option::Option<u32>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextMessage {
    #[prost(uint32, optional, tag = "1")]
    pub actor: ::core::option::Option<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "2")]
    pub session: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "3")]
    pub channel_id: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "4")]
    pub tree_id: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, required, tag = "5")]
    pub message: ::prost::alloc::string::String,
    /// Unique identifier for this message (Fancy Mumble extension).
    #[prost(string, optional, tag = "6")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Message timestamp as Unix epoch millis (Fancy Mumble extension).
    #[prost(uint64, optional, tag = "7")]
    pub timestamp: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PermissionDenied {
    #[prost(uint32, optional, tag = "1")]
    pub permission: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub session: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "permission_denied::DenyType", optional, tag = "5")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "6")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `PermissionDenied`.
pub mod permission_denied {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DenyType {
        Text = 0,
        Permission = 1,
        SuperUser = 2,
        ChannelName = 3,
        TextTooLong = 4,
        H9k = 5,
        TemporaryChannel = 6,
        MissingCertificate = 7,
        UserName = 8,
        ChannelFull = 9,
        NestingLimit = 10,
        ChannelCountLimit = 11,
        ChannelListenerLimit = 12,
        UserListenerLimit = 13,
    }
    impl DenyType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Text => "Text",
                Self::Permission => "Permission",
                Self::SuperUser => "SuperUser",
                Self::ChannelName => "ChannelName",
                Self::TextTooLong => "TextTooLong",
                Self::H9k => "H9K",
                Self::TemporaryChannel => "TemporaryChannel",
                Self::MissingCertificate => "MissingCertificate",
                Self::UserName => "UserName",
                Self::ChannelFull => "ChannelFull",
                Self::NestingLimit => "NestingLimit",
                Self::ChannelCountLimit => "ChannelCountLimit",
                Self::ChannelListenerLimit => "ChannelListenerLimit",
                Self::UserListenerLimit => "UserListenerLimit",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Text" => Some(Self::Text),
                "Permission" => Some(Self::Permission),
                "SuperUser" => Some(Self::SuperUser),
                "ChannelName" => Some(Self::ChannelName),
                "TextTooLong" => Some(Self::TextTooLong),
                "H9K" => Some(Self::H9k),
                "TemporaryChannel" => Some(Self::TemporaryChannel),
                "MissingCertificate" => Some(Self::MissingCertificate),
                "UserName" => Some(Self::UserName),
                "ChannelFull" => Some(Self::ChannelFull),
                "NestingLimit" => Some(Self::NestingLimit),
                "ChannelCountLimit" => Some(Self::ChannelCountLimit),
                "ChannelListenerLimit" => Some(Self::ChannelListenerLimit),
                "UserListenerLimit" => Some(Self::UserListenerLimit),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Acl {
    #[prost(uint32, required, tag = "1")]
    pub channel_id: u32,
    #[prost(bool, optional, tag = "2", default = "true")]
    pub inherit_acls: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "3")]
    pub groups: ::prost::alloc::vec::Vec<acl::ChanGroup>,
    #[prost(message, repeated, tag = "4")]
    pub acls: ::prost::alloc::vec::Vec<acl::ChanAcl>,
    #[prost(bool, optional, tag = "5", default = "false")]
    pub query: ::core::option::Option<bool>,
}
/// Nested message and enum types in `ACL`.
pub mod acl {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ChanGroup {
        #[prost(string, required, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(bool, optional, tag = "2", default = "true")]
        pub inherited: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "3", default = "true")]
        pub inherit: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "4", default = "true")]
        pub inheritable: ::core::option::Option<bool>,
        #[prost(uint32, repeated, packed = "false", tag = "5")]
        pub add: ::prost::alloc::vec::Vec<u32>,
        #[prost(uint32, repeated, packed = "false", tag = "6")]
        pub remove: ::prost::alloc::vec::Vec<u32>,
        #[prost(uint32, repeated, packed = "false", tag = "7")]
        pub inherited_members: ::prost::alloc::vec::Vec<u32>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ChanAcl {
        #[prost(bool, optional, tag = "1", default = "true")]
        pub apply_here: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "2", default = "true")]
        pub apply_subs: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "3", default = "true")]
        pub inherited: ::core::option::Option<bool>,
        #[prost(uint32, optional, tag = "4")]
        pub user_id: ::core::option::Option<u32>,
        #[prost(string, optional, tag = "5")]
        pub group: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "6")]
        pub grant: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "7")]
        pub deny: ::core::option::Option<u32>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryUsers {
    #[prost(uint32, repeated, packed = "false", tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CryptSetup {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub client_nonce: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub server_nonce: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContextActionModify {
    #[prost(string, required, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub context: ::core::option::Option<u32>,
    #[prost(enumeration = "context_action_modify::Operation", optional, tag = "4")]
    pub operation: ::core::option::Option<i32>,
}
/// Nested message and enum types in `ContextActionModify`.
pub mod context_action_modify {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Context {
        Server = 1,
        Channel = 2,
        User = 4,
    }
    impl Context {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Server => "Server",
                Self::Channel => "Channel",
                Self::User => "User",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Server" => Some(Self::Server),
                "Channel" => Some(Self::Channel),
                "User" => Some(Self::User),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Operation {
        Add = 0,
        Remove = 1,
    }
    impl Operation {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Add => "Add",
                Self::Remove => "Remove",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Add" => Some(Self::Add),
                "Remove" => Some(Self::Remove),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContextAction {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(string, required, tag = "3")]
    pub action: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserList {
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<user_list::User>,
}
/// Nested message and enum types in `UserList`.
pub mod user_list {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct User {
        #[prost(uint32, required, tag = "1")]
        pub user_id: u32,
        #[prost(string, optional, tag = "2")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub last_seen: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "4")]
        pub last_channel: ::core::option::Option<u32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoiceTarget {
    #[prost(uint32, optional, tag = "1")]
    pub id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub targets: ::prost::alloc::vec::Vec<voice_target::Target>,
}
/// Nested message and enum types in `VoiceTarget`.
pub mod voice_target {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Target {
        #[prost(uint32, repeated, packed = "false", tag = "1")]
        pub session: ::prost::alloc::vec::Vec<u32>,
        #[prost(uint32, optional, tag = "2")]
        pub channel_id: ::core::option::Option<u32>,
        #[prost(string, optional, tag = "3")]
        pub group: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(bool, optional, tag = "4", default = "false")]
        pub links: ::core::option::Option<bool>,
        #[prost(bool, optional, tag = "5", default = "false")]
        pub children: ::core::option::Option<bool>,
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PermissionQuery {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub permissions: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "3", default = "false")]
    pub flush: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CodecVersion {
    #[prost(int32, required, tag = "1")]
    pub alpha: i32,
    #[prost(int32, required, tag = "2")]
    pub beta: i32,
    #[prost(bool, required, tag = "3", default = "true")]
    pub prefer_alpha: bool,
    #[prost(bool, optional, tag = "4", default = "false")]
    pub opus: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserStats {
    #[prost(uint32, optional, tag = "1")]
    pub session: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "2", default = "false")]
    pub stats_only: ::core::option::Option<bool>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub certificates: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "4")]
    pub from_client: ::core::option::Option<user_stats::Stats>,
    #[prost(message, optional, tag = "5")]
    pub from_server: ::core::option::Option<user_stats::Stats>,
    #[prost(uint32, optional, tag = "6")]
    pub udp_packets: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub tcp_packets: ::core::option::Option<u32>,
    #[prost(float, optional, tag = "8")]
    pub udp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "9")]
    pub udp_ping_var: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "10")]
    pub tcp_ping_avg: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "11")]
    pub tcp_ping_var: ::core::option::Option<f32>,
    #[prost(message, optional, tag = "12")]
    pub version: ::core::option::Option<Version>,
    #[prost(int32, repeated, packed = "false", tag = "13")]
    pub celt_versions: ::prost::alloc::vec::Vec<i32>,
    #[prost(bytes = "vec", optional, tag = "14")]
    pub address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "15")]
    pub bandwidth: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "16")]
    pub onlinesecs: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "17")]
    pub idlesecs: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "18", default = "false")]
    pub strong_certificate: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "19", default = "false")]
    pub opus: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "20")]
    pub rolling_stats: ::core::option::Option<user_stats::RollingStats>,
}
/// Nested message and enum types in `UserStats`.
pub mod user_stats {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Stats {
        #[prost(uint32, optional, tag = "1")]
        pub good: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "2")]
        pub late: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "3")]
        pub lost: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "4")]
        pub resync: ::core::option::Option<u32>,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RollingStats {
        #[prost(uint32, optional, tag = "1")]
        pub time_window: ::core::option::Option<u32>,
        #[prost(message, optional, tag = "2")]
        pub from_client: ::core::option::Option<Stats>,
        #[prost(message, optional, tag = "3")]
        pub from_server: ::core::option::Option<Stats>,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestBlob {
    #[prost(uint32, repeated, packed = "false", tag = "1")]
    pub session_texture: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "2")]
    pub session_comment: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "3")]
    pub channel_description: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerConfig {
    #[prost(uint32, optional, tag = "1")]
    pub max_bandwidth: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub welcome_text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "3")]
    pub allow_html: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub message_length: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub image_message_length: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "6")]
    pub max_users: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "7")]
    pub recording_allowed: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SuggestConfig {
    #[prost(uint32, optional, tag = "1")]
    pub version_v1: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "4")]
    pub version_v2: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "2")]
    pub positional: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub push_to_talk: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginDataTransmission {
    #[prost(uint32, optional, tag = "1")]
    pub sender_session: ::core::option::Option<u32>,
    #[prost(uint32, repeated, tag = "2")]
    pub receiver_sessions: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "4")]
    pub data_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Encrypted persistent chat message sent from client to server for storage.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatMessage {
    #[prost(string, optional, tag = "1")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "3")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "4")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "PchatPersistenceMode", optional, tag = "5")]
    pub mode: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub envelope: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "7")]
    pub epoch: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "8")]
    pub chain_index: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "9")]
    pub epoch_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "10")]
    pub replaces_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Request stored messages from the server.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatFetch {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub before_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub limit: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub after_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Server response to a PchatFetch request.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PchatFetchResponse {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<PchatMessage>,
    #[prost(bool, optional, tag = "3")]
    pub has_more: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub total_stored: ::core::option::Option<u32>,
}
/// Server relays a new message to other clients in the channel.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatMessageDeliver {
    #[prost(string, optional, tag = "1")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "3")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "4")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "PchatPersistenceMode", optional, tag = "5")]
    pub mode: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub envelope: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "7")]
    pub replaces_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Client announcement of E2EE identity public keys.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyAnnounce {
    #[prost(uint32, optional, tag = "1")]
    pub algorithm_version: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub identity_public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub signing_public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "4")]
    pub cert_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "5")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "7")]
    pub tls_signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Peer-to-peer key exchange relayed through the server.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyExchange {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(enumeration = "PchatPersistenceMode", optional, tag = "2")]
    pub mode: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag = "3")]
    pub epoch: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub encrypted_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "5")]
    pub sender_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub recipient_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "8")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "9")]
    pub algorithm_version: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "10")]
    pub signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "11")]
    pub parent_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "12")]
    pub epoch_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "13")]
    pub countersignature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "14")]
    pub countersigner_hash: ::core::option::Option<::prost::alloc::string::String>,
}
/// Server-broadcast key request when a new member joins a persistent channel.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatKeyRequest {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(enumeration = "PchatPersistenceMode", optional, tag = "2")]
    pub mode: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub requester_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub requester_public: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "5")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "6")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "7")]
    pub relay_cap: ::core::option::Option<u32>,
}
/// Server acknowledgement of message storage.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatAck {
    #[prost(string, optional, tag = "1")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "PchatAckStatus", optional, tag = "2")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
/// Key custodian countersignature on an epoch transition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PchatEpochCountersig {
    #[prost(uint32, optional, tag = "1")]
    pub channel_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub epoch: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub epoch_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub parent_fingerprint: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "5")]
    pub signer_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub distributor_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "7")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "8")]
    pub countersignature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Persistence mode used in pchat runtime messages.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PchatPersistenceMode {
    PchatModePostJoin = 0,
    PchatModeFullArchive = 1,
}
impl PchatPersistenceMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PchatModePostJoin => "PCHAT_MODE_POST_JOIN",
            Self::PchatModeFullArchive => "PCHAT_MODE_FULL_ARCHIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PCHAT_MODE_POST_JOIN" => Some(Self::PchatModePostJoin),
            "PCHAT_MODE_FULL_ARCHIVE" => Some(Self::PchatModeFullArchive),
            _ => None,
        }
    }
}
/// Ack status for PchatAck.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PchatAckStatus {
    PchatAckStored = 0,
    PchatAckRejected = 1,
    PchatAckQuotaExceeded = 2,
}
impl PchatAckStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PchatAckStored => "PCHAT_ACK_STORED",
            Self::PchatAckRejected => "PCHAT_ACK_REJECTED",
            Self::PchatAckQuotaExceeded => "PCHAT_ACK_QUOTA_EXCEEDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PCHAT_ACK_STORED" => Some(Self::PchatAckStored),
            "PCHAT_ACK_REJECTED" => Some(Self::PchatAckRejected),
            "PCHAT_ACK_QUOTA_EXCEEDED" => Some(Self::PchatAckQuotaExceeded),
            _ => None,
        }
    }
}
