/* AUTO-GENERATED by mumble-tauri/build.rs from
 * crates/fancy-utils/src/permissions.rs - DO NOT EDIT BY HAND.
 *
 * To add or change a Mumble permission flag, edit the Rust file and
 * rebuild; this file will be regenerated automatically.
 */

/** One Mumble ACL permission flag. */
export interface PermissionDef {
  /** Bitmask value (single bit). */
  readonly bit: number;
  /** Stable identifier matching the Rust constant name. */
  readonly ident: string;
  /** Human-readable label shown in the UI. */
  readonly label: string;
  /** True for permissions that only apply on the root channel. */
  readonly rootOnly: boolean;
}

// Named bit constants - one per Mumble ACL permission.
export const PERM_WRITE = 0x1;
export const PERM_TRAVERSE = 0x2;
export const PERM_ENTER = 0x4;
export const PERM_SPEAK = 0x8;
export const PERM_MUTE_DEAFEN = 0x10;
export const PERM_MOVE = 0x20;
export const PERM_MAKE_CHANNEL = 0x40;
export const PERM_LINK_CHANNEL = 0x80;
export const PERM_WHISPER = 0x100;
export const PERM_TEXT_MESSAGE = 0x200;
export const PERM_MAKE_TEMP_CHANNEL = 0x400;
export const PERM_LISTEN = 0x800;
export const PERM_DELETE_MESSAGE = 0x1000;
export const PERM_SUBSCRIBE_PUSH = 0x2000;
export const PERM_SHARE_FILES = 0x4000;
export const PERM_SHARE_FILES_PUBLIC = 0x8000;
export const PERM_KICK = 0x10000;
export const PERM_BAN = 0x20000;
export const PERM_REGISTER = 0x40000;
export const PERM_SELF_REGISTER = 0x80000;
export const PERM_RESET_USER_CONTENT = 0x100000;
export const PERM_KEY_OWNER = 0x200000;
export const PERM_MANAGE_EMOTES = 0x400000;

/** Complete ordered list of Mumble permission bits. */
export const PERMISSIONS: readonly PermissionDef[] = [
  { bit: PERM_WRITE, ident: "WRITE", label: "Write", rootOnly: false },
  { bit: PERM_TRAVERSE, ident: "TRAVERSE", label: "Traverse", rootOnly: false },
  { bit: PERM_ENTER, ident: "ENTER", label: "Enter", rootOnly: false },
  { bit: PERM_SPEAK, ident: "SPEAK", label: "Speak", rootOnly: false },
  { bit: PERM_MUTE_DEAFEN, ident: "MUTE_DEAFEN", label: "Mute/Deafen", rootOnly: false },
  { bit: PERM_MOVE, ident: "MOVE", label: "Move", rootOnly: false },
  { bit: PERM_MAKE_CHANNEL, ident: "MAKE_CHANNEL", label: "Make Channel", rootOnly: false },
  { bit: PERM_LINK_CHANNEL, ident: "LINK_CHANNEL", label: "Link Channel", rootOnly: false },
  { bit: PERM_WHISPER, ident: "WHISPER", label: "Whisper", rootOnly: false },
  { bit: PERM_TEXT_MESSAGE, ident: "TEXT_MESSAGE", label: "Text Message", rootOnly: false },
  { bit: PERM_MAKE_TEMP_CHANNEL, ident: "MAKE_TEMP_CHANNEL", label: "Make Temp Channel", rootOnly: false },
  { bit: PERM_LISTEN, ident: "LISTEN", label: "Listen", rootOnly: false },
  { bit: PERM_DELETE_MESSAGE, ident: "DELETE_MESSAGE", label: "Delete Message", rootOnly: false },
  { bit: PERM_SUBSCRIBE_PUSH, ident: "SUBSCRIBE_PUSH", label: "Subscribe Push", rootOnly: false },
  { bit: PERM_SHARE_FILES, ident: "SHARE_FILES", label: "Share Files", rootOnly: false },
  { bit: PERM_SHARE_FILES_PUBLIC, ident: "SHARE_FILES_PUBLIC", label: "Share Files (Public)", rootOnly: false },
  { bit: PERM_KICK, ident: "KICK", label: "Kick", rootOnly: true },
  { bit: PERM_BAN, ident: "BAN", label: "Ban", rootOnly: true },
  { bit: PERM_REGISTER, ident: "REGISTER", label: "Register", rootOnly: true },
  { bit: PERM_SELF_REGISTER, ident: "SELF_REGISTER", label: "Self-Register", rootOnly: true },
  { bit: PERM_RESET_USER_CONTENT, ident: "RESET_USER_CONTENT", label: "Reset User Content", rootOnly: true },
  { bit: PERM_KEY_OWNER, ident: "KEY_OWNER", label: "Key Owner", rootOnly: true },
  { bit: PERM_MANAGE_EMOTES, ident: "MANAGE_EMOTES", label: "Manage Emotes", rootOnly: true },
] as const;

/** Subset of permissions that apply to non-root channels. */
export const CHANNEL_PERMISSIONS: readonly PermissionDef[] =
  PERMISSIONS.filter((p) => !p.rootOnly);

/** Subset of permissions that only apply to the root channel. */
export const ROOT_PERMISSIONS: readonly PermissionDef[] =
  PERMISSIONS.filter((p) => p.rootOnly);
