// Centralised icon barrel.
//
// All icons are re-exported from `lucide-react` (https://lucide.dev) under
// the legacy display names previously used by the per-file
// `assets/icons/*.svg?react` imports. This means consumer components can
// keep using `<MicIcon />` etc. without any JSX changes — only the import
// line needs to point at this barrel.
//
// To add a new icon, look it up at https://lucide.dev/icons and add a
// re-export here. Lucide ships ~1500 icons (MIT, actively maintained), so
// it should be the only icon source going forward — please do not add any
// more inline SVGs or per-icon asset files.

export {
  Paperclip as AttachIcon,
  ArrowUpRight as ArrowUpRightIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  Ban as BlockIcon,
  SquareCheck as CheckboxIcon,
  CheckCheck as CheckDoubleIcon,
  Check as CheckIcon,
  Check as CheckSingleIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  X as CloseIcon,
  Copy as CopyIcon,
  Database as DatabaseIcon,
  Pencil as EditIcon,
  SmilePlus as EmojiPlusIcon,
  CircleAlert as ErrorCircleIcon,
  Folder as FolderIcon,
  Minimize as FullscreenExitIcon,
  Maximize as FullscreenIcon,
  FileImage as GifIcon,
  Grid2x2 as Grid2x2Icon,
  Hash as HashIcon,
  Headphones as HeadphonesIcon,
  HeadphoneOff as HeadphonesOffIcon,
  Image as ImageIcon,
  Info as InfoFilledIcon,
  Info as InfoIcon,
  EllipsisVertical as KebabMenuIcon,
  Key as KeyIcon,
  Ear as ListenBadgeIcon,
  Lock as LockSvg,
  LogOut as LogoutIcon,
  Maximize2 as MaximizeIcon,
  Menu as MenuIcon,
  MessageSquare as MessageIcon,
  MessageSquareOff as MessageMinusIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  MicOff as MicOffSmallIcon,
  Minus as MinimizeIcon,
  Moon as MoonIcon,
  Pause as PauseIcon,
  Phone as PhoneIcon,
  PhoneOff as PhoneOffIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  ChartBar as PollIcon,
  Quote as QuoteIcon,
  Disc as RecordIcon,
  RefreshCw as RefreshCwIcon,
  RotateCw as RefreshIcon,
  ScreenShare as ScreenShareIcon,
  Search as SearchIcon,
  Send as SendIcon,
  Server as ServerIcon,
  Settings as SettingsIcon,
  ShieldCheck as ShieldCheckIcon,
  ShieldCheck as ShieldCheckSvg,
  Shield as ShieldIcon,
  Star as StarIcon,
  File as FileIcon,
  Trash2 as TrashIcon,
  UserRound as UserFilledIcon,
  User as UserIcon,
  UserPlus as UserPlusIcon,
  Users as UsersGroupIcon,
  UserX as UserXIcon,
  Volume2 as VolumeIcon,
  VolumeX as VolumeOffIcon,
  TriangleAlert as WarningFilledIcon,
  TriangleAlert as WarningIcon,
  TriangleAlert as WarningSvg,
  X as WindowCloseIcon,
} from "lucide-react";
